server:
  port: 8084

spring:
  application:
    name: inventory-service-dlq
  main:
    web-application-type: reactive

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-dlq-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # BUG-05 FIX: Bổ sung trusted.packages=* cho phép Kafka tự động giải mã Object JSON an toàn
        spring.json.trusted.packages: "*"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    topic:
      order-events: storex-order-events
      order-dlq: storex-order-events.DLQ
